#!/bin/bash

bin/c_parser : obj/c_lexer.yy.o obj/c_parser.tab.o
	g++ -o bin/c_parser obj/c_parser.tab.o obj/c_lexer.yy.o

obj/c_lexer.yy.o : src/c_lexer.yy.c src/c_parser.tab.h
	g++ -o obj/c_lexer.yy.o -c src/c_lexer.yy.c

obj/c_parser.tab.o : src/c_parser.tab.h src/c_parser.tab.c
	g++ -o obj/c_parser.tab.o -c src/c_parser.tab.c

src/c_parser.tab.h : src/c_parser.y
	bison -o src/c_parser.tab.h -d src/c_parser.y

src/c_parser.tab.c : src/c_parser.y
	bison -o src/c_parser.tab.c -d src/c_parser.y

src/c_lexer.yy.c : src/c_lexer.l
	flex -o src/c_lexer.yy.c src/c_lexer.l

clean :
	#rm bin/c_parser
	rm obj/c_lexer.yy.o 
	rm obj/c_parser.tab.o
	rm src/c_parser.tab.h
	rm src/c_parser.tab.c
	rm src/c_lexer.yy.c


